# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptctl < Formula
  desc "CLI for managing secrets to be used with encrypted-secrets"
  homepage "https://github.com/shubhindia/cryptctl"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.4/cryptctl-0.0.4-darwin-amd64.tar.gz"
      sha256 "a97c20ad4f43089aa1d29671d23aecb92281cb865cdba0227afed94e4c66575f"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.4/cryptctl-0.0.4-darwin-arm64.tar.gz"
      sha256 "d10b888eac036af5080528a16cb60c8d8e48fffce03df656806a9b15c5abfe42"

      def install
        bin.install "cryptctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.4/cryptctl-0.0.4-linux-arm64.tar.gz"
      sha256 "62426cb6104d99f81edbbbf7833e90ddd39ee612c67d5a97406808ed09bb9384"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.4/cryptctl-0.0.4-linux-amd64.tar.gz"
      sha256 "057ca43a060736b140867339b9bb9bb47e97050dac099400890cf269638b4217"

      def install
        bin.install "cryptctl"
      end
    end
  end
end
