# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptctl < Formula
  desc "CLI for managing secrets to be used with encrypted-secrets"
  homepage "https://github.com/shubhindia/cryptctl"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.2/cryptctl-0.0.2-darwin-amd64.tar.gz"
      sha256 "afec10815b24e1de8fe3a219a0cc32fc1484090c650167eefdabb8549ef7611f"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.2/cryptctl-0.0.2-darwin-arm64.tar.gz"
      sha256 "5456ff53d29a38b298ccf3e26a5f5d5c0aaae0c462f03135de77284d448f9bde"

      def install
        bin.install "cryptctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.2/cryptctl-0.0.2-linux-amd64.tar.gz"
      sha256 "edd85b754c7285bf137134159f03e68f2d7bb4e716c1ec98635d87ce1e607a11"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.2/cryptctl-0.0.2-linux-arm64.tar.gz"
      sha256 "8d5c0e7523393cb2e76639875e9b730487ec4b49be2a3effe67f98a0697d2afe"

      def install
        bin.install "cryptctl"
      end
    end
  end
end
