# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptctl < Formula
  desc "CLI for managing secrets to be used with encrypted-secrets"
  homepage "https://github.com/shubhindia/cryptctl"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.3/cryptctl-0.0.3-darwin-arm64.tar.gz"
      sha256 "41b27d92fe14bfddd6f1973cd6513ed6506b1c233eb9d19c633c70b2f3650ae3"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.3/cryptctl-0.0.3-darwin-amd64.tar.gz"
      sha256 "76a07206e1272de80dcba3400bea815f773aeffdaa5f56d8d2f015e988001bf5"

      def install
        bin.install "cryptctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.3/cryptctl-0.0.3-linux-arm64.tar.gz"
      sha256 "7207d8afedb3e8bff8a095838f174be8afbc2a853ddb052a421bc55eaf943c48"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhindia/cryptctl/releases/download/v0.0.3/cryptctl-0.0.3-linux-amd64.tar.gz"
      sha256 "160c96a10d0ae22567f2ff84ce76563a2bf4eafa3de1904bcd1c36a166de241e"

      def install
        bin.install "cryptctl"
      end
    end
  end
end
